name: Deploy to server

on: push
env:
    WORKFLOW_VAR: variable workflow
    GENERAL_VAR: variable general

jobs:
    first-job:
        if: false
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo"

    second-job:
        if: false
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hola Mundo 2
              run: echo "Hola Mundo 2"

    third-job:
        # Se ejecuta si la referencia es master
        # if: ${{ github.ref == 'refs/heads/master' }}
        if: false
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.ref }}
            - run: echo ${{ github.ref_name }}
    
    fourth-job:
        if: false
        runs-on: ubuntu-latest
        env:
            JOB_VAR: variable de job
            GENERAL_VAR: variable general del job 
        steps:
            - name: step1
              env:
                STEP_VAR: variable de step
                GENERAL_VAR: variable general de step
              run: |
                echo "${{ env.WORKFLOW_VAR }}"
                echo "${{ env.JOB_VAR }}"
                echo "${{ env.STEP_VAR }}"
                echo "${{ env.GENERAL_VAR }}"

    # Uso de acciones
    fifth-job:
        if: false
        runs-on: ubuntu-latest
        steps:
            - name: Working dir
              run: ls -al
            - name: Checkout action
              # te posiciona donde se encuentra el repo actual
              uses: actions/checkout@v4
            - name: Working dir
              run: ls -al

    # Paso de valores entre steps
    sixth-job:
        if: false
        runs-on: ubuntu-latest
        outputs:
            my-variable: ${{ steps.set_variable.outputs.my-variable }}
        steps:
            - name: Set variable
              id: set_variable
              run: echo "my-variable=HolaMundo" >> $GITHUB_OUTPUT

            - name: Obtener mensaje del paso anterior
              run: echo "${{ steps.set_variable.outputs.my-variable }}"

    seventh-job:
        if: false
        needs: sixth-job
        runs-on: ubuntu-latest
        env:
            MY_VAR: ${{ needs.sixth-job.outputs.my-variable }}
        steps:
            - name: Reading shared variable
              run: echo "${{ env.MY_VAR }}"

    eighth-job:
        runs-on: ubuntu-latest
        steps:
            - name: Generar archivo
              run: |
                echo "Archivo de prueba" >> archivo.log
            
            - name: Subir artefacto
              uses: actions/upload-artifact@v4
              with:
                name: archivo-log
                path: archivo.log
