name: Deploy to server

on: push
env:
    WORKFLOW_VAR: variable workflow
    GENERAL_VAR: variable general

jobs:
    first-job:
        if: false
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo"

    second-job:
        if: false
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Hola Mundo 2
              run: echo "Hola Mundo 2"

    third-job:
        # Se ejecuta si la referencia es master
        if: ${{ github.ref == 'refs/heads/master' }}
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ github.ref }}
            - run: echo ${{ github.ref_name }}
    
    fourth-job:
        if: false
        runs-on: ubuntu-latest
        env:
            JOB_VAR: variable de job
            GENERAL_VAR: variable general del job 
        steps:
            - name: step1
              env:
                STEP_VAR: variable de step
                GENERAL_VAR: variable general de step
              run: |
                echo "${{ env.WORKFLOW_VAR }}"
                echo "${{ env.JOB_VAR }}"
                echo "${{ env.STEP_VAR }}"
                echo "${{ env.GENERAL_VAR }}"

    # Uso de acciones
    fifth-job:
        runs-on: ubuntu-latest
        steps:
            - name: Working dir
              run: ls -al
            - name: Checkout action
              # te posiciona donde se encuentra el repo actual
              uses: actions/checkout@v4
            - name: Working dir
              run: ls -al
