name: Strategy

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        # Ejecutará este job tantas veces como elementos en la matriz
        strategy:
            matrix:
                # Genera todas las combinaciones posibles
                message: ['Hola', 'DamiánRi', 'Github Actions']
                version: [v1, v2, v3]
        steps:
            - name: Print message
              run: echo "${{ matrix.message}}${{ matrix.version}}"